cat <<EOF > $HOME/.gitconfig
# This gitconfig was generated by my-bash-env

[user]
  name = $MY_BASH_ENV_NAME
  email = $MY_BASH_ENV_EMAIL

[push]
	default = simple

[alias]
  s = status
	lg = log --all --graph --pretty='%h %C(cyan)%cd %C(auto)%d %C(bold yellow)%an%n%C(reset)%<(139,trunc)%s%n'

[merge]
    tool = kdiff3

[mergetool "kdiff3"]
    path = /usr/local/bin/kdiff3

[diff]
    tool = kdiff3

[difftool "kdiff3"]
    path = /usr/local/bin/kdiff3
EOF
