cat <<EOF > $HOME/.gitconfig
# This gitconfig was generated by my-bash-env

[user]
  name = $MY_BASH_ENV_NAME
  email = $MY_BASH_ENV_EMAIL

[push]
	default = simple

[color]
  ui = true

[alias]
  s = status
  st = status --short
  co = checkout
  br = branch
  last = log -1 --stat
	lg = log --all --graph --pretty='%h %C(cyan)%cd %C(auto)%d %C(bold yellow)%an%n%C(reset)%<(139,trunc)%s%n'

[merge]
  tool = kdiff3

[diff]
  tool = kdiff3

[difftool]
  prompt = false

EOF
