cat <<EOF > $HOME/.gitconfig
# This gitconfig was generated by my-bash-env

[user]
  name = $MY_BASH_ENV_NAME
  email = $MY_BASH_ENV_EMAIL

[push]
  default = simple

[color]
  ui = true

[alias]
  s = status
  st = status --short
  co = checkout
  br = branch
  last = log -1 --stat
  lg = log --all --graph --pretty='%h %C(cyan)%cd %C(auto)%d %C(bold yellow)%an%n%C(reset)%<(139,trunc)%s%n'

[log]
  date = format:'%Y-%m-%d %H:%M'

[merge]
  tool = kdiff3
  conflictstyle = diff3

[diff]
  tool = code

[difftool]
  prompt = false

[difftool "code"]
  cmd = code --wait --diff \$LOCAL \$REMOTE

[mergetool "meld"]
  cmd = meld \$LOCAL \$BASE \$REMOTE -o \$MERGED --diff \$BASE \$LOCAL --diff \$BASE \$REMOTE --auto-merge

[mergetool "code"]
    cmd = code --wait \$MERGED

EOF

# Git completion
_git_review () {
   __gitcomp_nl "$(__git_refs)"
}
